version: "3.8"

services:
  udp-client:    
    build:
      context: .
      dockerfile: Dockerfile  # Points to the Dockerfile for the UDP client
    ports:
      - "9803:9801/udp"  # Expose the UDP port to the host
      - "7802:9803/tcp"  # Expose the TCP port to the host (this port is used by the TCP server to communicate)
    stdin_open: true
    tty: true
    restart: always